### ISSUE TITLE
Unable use Mongodb connection

### ISSUE THREAD

**Issue by krishnakalyan3** [NovaSyst/chocolate#2]
Hello,
I am using chocolate to search over my parameter space, Currently I am unable to import `MongoDBConnection ` libraries.

Error below:
```
Traceback (most recent call last):
  File "svm_opt.py", line 40, in <module>
    conn = choco.MongoDBConnection(url="mongodb://127.0.0.1:27017")
AttributeError: module 'chocolate' has no attribute 'MongoDBConnection'
```

Another question : why is it mandatory to connect to a database?. (Maybe I am missing something?. It would have been easier to get started without the overhead of installing Mongodb or SQLLite)

Thanks

**Comment by fmder** [comment]
Sorry if this is way too basic, but have you installed pymongo? It is not
in the hard dependencies.

Moreover, if you are working on a single file system, we encourage you to
use the sqlite connection. This is the most tested one.

Le 27 févr. 2017 06:57, "Krishna Kalyan" <notifications@github.com> a
écrit :

**Comment by krishnakalyan3** [comment]
@fmder Thank you. I did not have pymongo installed. If required I can submit a pull request with pymongo as a hard dependency.
